import { AdSlot } from "@/components/AdSlot";

const WINDOWS_DOWNLOAD="https://github.com/VenkataAnnabathula/fitness-tracker/releases/download/v0.6.0-beta/The-Caffeinate-0.6.0-windows-x64.exe";
const SOURCE_URL=process.env.NEXT_PUBLIC_SOURCE_URL;

const features=[
 {number:"01",title:"Edit native PDF text",copy:"Correct text, add notes, highlight details, whiteout content, and preview the finished result without a watermark."},
 {number:"02",title:"Organize every page",copy:"Merge documents, split page ranges, rotate pages, remove what you do not need, and export a fresh copy."},
 {number:"03",title:"Extract for AI",copy:"Use bundled offline OCR to turn scans into focused TXT or structured Markdown without sending the document to an AI provider."},
 {number:"04",title:"Convert and compress",copy:"Convert images and PDF pages or shrink image-heavy documents using the desktop app and your own hardware."},
];

const privacyFacts=[
 ["Desktop stays local","PDFs, OCR, edits, and exports remain on your computer."],
 ["Web stays in your browser","The web editor processes PDFs in this browser tab without uploading them to us."],
 ["No document targeting","Ads never receive filenames, extracted text, page images, or editing history."],
 ["Open-source direction","The next PyMuPDF build ships under GNU AGPL v3 with corresponding source."],
];

function BrandMark(){return <span className="brand-mark" aria-hidden="true"><i/><i/><i/></span>}
function Arrow(){return <span aria-hidden="true">↗</span>}

export default function Home(){return <div className="site-shell">
 <div className="free-banner">100% free · No watermarks · No premium feature gates</div>
 <header className="nav-wrap"><a className="wordmark" href="#top"><BrandMark/><span>The Caffeinate</span></a><nav aria-label="Main navigation"><a href="/editor">Web editor</a><a href="#features">Features</a><a href="#ai-ready">AI-ready</a><a href="#privacy">Privacy</a></nav><a className="nav-cta" href="/editor">Edit a PDF <Arrow/></a></header>
 <main id="top">
  <section className="hero section-pad"><div className="hero-copy"><div className="eyebrow"><span className="pulse"/> Free, private PDF editing</div><h1>Wake up your PDFs.<br/><em>Keep them yours.</em></h1><p className="hero-lede">Edit PDFs now in your browser, or use the desktop app for offline OCR and larger workflows. Free, with no watermark or subscription.</p><div className="hero-actions"><a className="primary-button" href="/editor">Open web editor <span>↗</span></a><a className="text-button" href="#download">Get desktop app <span>↓</span></a>{SOURCE_URL&&<a className="text-button" href={SOURCE_URL} target="_blank" rel="noreferrer">View source <Arrow/></a>}</div><div className="hero-note"><span>◆</span> No account · No upload in the web editor · No feature gates</div></div>
   <div className="product-scene" aria-label="Preview of The Caffeinate PDF editor"><div className="editor-window"><div className="editor-topbar"><div className="mini-brand"><BrandMark/><span>proposal.pdf</span></div><div className="editor-tools"><span>Edit</span><span>Text</span><span>Highlight</span><span>PDF Tools</span></div><b>Export PDF</b></div><div className="editor-body"><aside className="page-rail"><small>Pages</small>{[1,2,3].map(page=><div className={`mini-page ${page===2?"active":""}`} key={page}><i/><span>{page}</span></div>)}</aside><div className="document-stage"><div className="page-chip">Page 2 of 3 · Scroll continuously</div><article className="paper"><div className="paper-kicker">Project proposal</div><div className="paper-title">A calmer way to<br/>work with documents.</div><div className="paper-rule"/><p>Private files should stay private. Make the changes you need, then save a fresh searchable copy.</p><div className="highlight-line">Processed locally in the desktop app.</div><div className="paper-lines"><i/><i/><i/></div></article></div><aside className="properties-panel"><small>Properties</small><div className="property-empty"><b>Aa</b><span>Select text to edit its content and appearance.</span></div></aside></div></div><div className="floating-card float-private"><span className="status-icon">✓</span><div><b>Desktop stays local</b><small>0 document uploads</small></div></div><div className="floating-card float-tools"><span>FREE · AI-READY</span><b>OCR · TXT · Markdown</b></div></div>
  </section>
  <section className="trust-strip"><span>Free forever</span><i/><span>Browser-local web editor</span><i/><span>No watermarks</span><i/><span>Source available under AGPL</span></section>
  <AdSlot slot="NEXT_PUBLIC_ADSENSE_TOP_SLOT"/>
  <section className="feature-section section-pad" id="features"><div className="section-heading"><div><span className="section-label">Everything included</span><h2>One focused workspace.<br/>No upgrade screen.</h2></div><p>Every shipped PDF feature is available to every user. Advertising and disclosed affiliate sponsorship—not locked tools—support development.</p></div><div className="feature-grid">{features.map(feature=><article className="feature-card" key={feature.number}><span>{feature.number}</span><h3>{feature.title}</h3><p>{feature.copy}</p><div className={`feature-visual visual-${feature.number}`}><i/><i/><i/></div></article>)}</div></section>
  <section className="ai-section section-pad" id="ai-ready"><div className="ai-copy"><span className="section-label">Built for your AI workflow</span><h2>Give AI the useful text.<br/><em>Leave out the clutter.</em></h2><p>Extract scanned PDFs locally into reusable text or Markdown, remove repeated page noise, and estimate document size before using the AI tool you prefer.</p><ul><li>Bundled offline OCR—no separate setup</li><li>Plain text and structured Markdown exports</li><li>Repeated header, footer, and page-number cleanup</li><li>No PDF content shared with advertisers</li></ul><small>Cleaner input can reduce unnecessary token usage. Actual token counts vary by model.</small></div><div className="ai-card"><div className="ai-card-top"><span>AI-READY EXPORT</span><b>Processed locally</b></div><div className="ai-file"><span>annual-report.pdf</span><b>86 pages</b></div><div className="ai-arrow">↓</div><div className="ai-output"><div><span>SELECTED</span><b>14 pages</b></div><div><span>CLEAN TEXT</span><b>18,420 words</b></div><div><span>ESTIMATED INPUT</span><b>≈ 25,000 tokens</b></div></div><div className="ai-removed"><span>✓ Headers removed</span><span>✓ Page numbers removed</span><span>✓ .md or .txt</span></div></div></section>
  <section className="pricing-section section-pad" id="free"><div className="section-heading"><div><span className="section-label">A simpler model</span><h2>$0. Every feature.<br/>No catch in the export.</h2></div><p>The Caffeinate is moving to a public-source, ad-supported model so useful PDF tools remain accessible without subscriptions.</p></div><div className="pricing-grid"><article className="featured-plan"><div className="founding-badge">EVERYONE</div><span className="plan-name">FREE FOREVER</span><h3>$0</h3><p>No watermark</p><ul><li>Native PDF text editing</li><li>Offline OCR and AI-ready export</li><li>Merge, split, compress, and convert</li><li>No local feature gates or license keys</li><li>Windows and macOS builds as released</li></ul><a href="#download">Get The Caffeinate <Arrow/></a></article><article><span className="plan-name">OPEN SOURCE</span><h3>AGPL v3</h3><p>For the next PyMuPDF build</p><ul><li>Corresponding source for every distributed build</li><li>Public build scripts and dependency manifests</li><li>Community inspection and contribution</li><li>No proprietary premium layer</li></ul>{SOURCE_URL?<a href={SOURCE_URL} target="_blank" rel="noreferrer">Browse source <Arrow/></a>:<span className="source-pending">Repository publication in progress</span>}</article><article><span className="plan-name">SUPPORTED RESPONSIBLY</span><h3>Ads + affiliates</h3><p>Clearly labeled</p><ul><li>Web ads stay away from editing controls</li><li>Desktop uses direct sponsor placements</li><li>No document-based ad targeting</li><li>No click required to export</li></ul><a href="mailto:hello@thecaffeinate.com?subject=Sponsor%20The%20Caffeinate">Sponsor the project <Arrow/></a></article></div></section>
  <section className="privacy-section section-pad" id="privacy"><div className="privacy-orbit" aria-hidden="true"><div className="orbit-ring ring-one"/><div className="orbit-ring ring-two"/><div className="privacy-core"><BrandMark/><b>YOUR PDF</b><span>stays yours</span></div><span className="orbit-tag tag-cloud">No document upload</span><span className="orbit-tag tag-account">No account</span><span className="orbit-tag tag-tracking">No content targeting</span></div><div className="privacy-copy"><span className="section-label light">Privacy without vague promises</span><h2>Two local modes.<br/>One clear promise.</h2><p>The desktop app processes documents on your computer. The web editor runs MuPDF inside your browser tab. Neither mode sends your selected PDF to The Caffeinate.</p><div className="privacy-list">{privacyFacts.map(([title,copy])=><div key={title}><span>✓</span><p><b>{title}</b>{copy}</p></div>)}</div><a href="/privacy">Read the privacy policy <Arrow/></a></div></section>
  <section className="workflow-section section-pad"><div className="section-heading compact"><div><span className="section-label">The desktop workflow</span><h2>Open. Edit. Preview. Save.</h2></div></div><div className="workflow"><div><span>1</span><b>Open locally</b><p>Choose a PDF from your computer.</p></div><i>→</i><div><span>2</span><b>Edit natively</b><p>Correct text and organize pages.</p></div><i>→</i><div><span>3</span><b>Preview first</b><p>Review the finished document.</p></div><i>→</i><div><span>4</span><b>Save anywhere</b><p>Export a fresh searchable copy.</p></div></div></section>
  <AdSlot slot="NEXT_PUBLIC_ADSENSE_BOTTOM_SLOT"/>
  <section className="products-section section-pad" id="products"><div className="section-heading"><div><span className="section-label">The Caffeinate collection</span><h2>Small utilities.<br/>Serious privacy.</h2></div><p>PDF is the first utility in a family of focused free tools designed to respect your files and attention.</p></div><div className="product-row"><a className="product-current" href="/editor"><div><span>USE IT NOW</span><h3>Web PDF Editor</h3><p>Edit locally in your browser—no upload required.</p></div><BrandMark/></a><article><span>DESKTOP BETA</span><h3>PDF Desktop</h3><p>Offline OCR and deeper document workflows.</p></article><article><span>COMING NEXT</span><h3>Images</h3><p>Resize, convert, compress, and clean up images locally.</p></article></div></section>
  <section className="download-section section-pad" id="download"><div className="download-copy"><span className="section-label light">Free desktop beta</span><h2>Your PDF workspace is ready.</h2><p>The current Windows beta is free. The new PyMuPDF-powered AGPL build will replace it after source publication and release verification.</p><div className="beta-warning">The Windows beta is unsigned, so Windows may show a warning. Keep backups and review exported files. Mac is coming after signing and notarization.</div></div><div className="download-cards"><div className="download-card coming-soon-card"><span className="platform-icon apple">●</span><div><small>MACOS · APPLE SILICON</small><b>Mac version coming soon</b><em>Signing and notarization pending</em></div><span className="soon-pill">SOON</span></div><a href={WINDOWS_DOWNLOAD} className="download-card"><span className="platform-icon windows"><i/><i/><i/><i/></span><div><small>FOR 64-BIT WINDOWS</small><b>Download current free beta</b><em>Windows 10 or 11 · OCR included</em></div><Arrow/></a><p>By downloading, you agree to the <a href="/terms">beta terms</a>. Need help? <a href="mailto:hello@thecaffeinate.com">hello@thecaffeinate.com</a></p></div></section>
 </main>
 <footer><div><a className="wordmark footer-brand" href="#top"><BrandMark/><span>The Caffeinate</span></a><p>Free utilities for files that should stay yours.</p></div><div className="footer-links"><div><b>Product</b><a href="/editor">Web editor</a><a href="#features">Features</a><a href="#download">Downloads</a></div><div><b>Trust</b><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/refunds">Payments</a></div><div><b>Contact</b><a href="mailto:hello@thecaffeinate.com">Email us</a><a href="mailto:hello@thecaffeinate.com?subject=Sponsor%20The%20Caffeinate">Sponsor</a>{SOURCE_URL&&<a href={SOURCE_URL} target="_blank" rel="noreferrer">Source code</a>}</div></div><div className="footer-bottom"><span>© 2026 The Caffeinate</span><span>Free. Browser-local. Open source.</span></div></footer>
 </div>}
